### ISSUE TITLE
请问BERT的输入是什么？

### ISSUE THREAD

**Issue by MiaoHu-Pro** [zhw12/BERTRL#1]
你好，

1. 请问这篇文章被哪个期刊或会议录用了？

2. 读了这篇论文，不是很理解BERT的输入是什么？

3.你的论文中 unseen relation 指的是什么？不是很理解。

希望您有空的时候，帮我解决上述疑问，谢谢。

Miao

**Comment by zhw12** [comment]
您好，论文现在还在投稿状态。 BERT的输入是target triple 和reasoning path文本的拼接, load_data.py文件从KG triple生成了具体的BERT输入。在训练阶段，每个target triple会和多个reasoning path构成多个正/负样本(如文中所述)。在测试阶段, 每个target triple与其reasoning paths组合产生多个分数。最后这些分数被聚合。 unseen relation指的是训练集里没有出现的relation, 在这个设置下，测试集里元组的relation和训练集元组里的relation不重合。
