### ISSUE TITLE
Missing File: "cached_train_BertTokenizerFast_128_mrpc.lock"

### ISSUE THREAD

**Issue by WWW2025AnonymousSubmission** [zhw12/BERTRL#2]
Hi Hanwen,

I'm very interested in your work and want to know more details using your code implementation.

However, when I run the code by myself, one problem occurs:

Traceback (most recent call last):
  File "run_bertrl.py", line 320, in <module>
    main()
  File "run_bertrl.py", line 135, in main
    GlueDataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
  File "/home/zhixiang/miniconda3/envs/py36/lib/python3.6/site-packages/transformers/data/datasets/glue.py", line 121, in __init__
    with FileLock(lock_path):
  File "/home/zhixiang/miniconda3/envs/py36/lib/python3.6/site-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/zhixiang/miniconda3/envs/py36/lib/python3.6/site-packages/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/zhixiang/miniconda3/envs/py36/lib/python3.6/site-packages/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'bertrl_data/fb237_hop3_full_neg10_max_inductive/cached_train_BertTokenizerFast_128_mrpc.lock'

This may due to the transformers version. Since version 3.3.1 is not available, I tried the latest version 4.18.0.
Could you please give me some suggestions to fix it?

**Comment by zhw12** [comment]
Thanks for the interest! I am not sure if it's a huggingface transformers version issue. Did you try to run the data preprocessing script like following to prepare the tsv dataset? I only uploaded one dataset split as an example.
`python load_data.py -d $DATASET -st train --part full --hop 3 --ind_suffix "_ind" --suffix "_neg10_path3_max_inductive"`

**Comment by WWW2025AnonymousSubmission** [comment]
Is it supposed to be like this:

python load_data.py -d fb237 -st dev --part full --hop 3 --ind_suffix "_ind" --suffix **"_neg10_max_inductive"**  

When I checked file 'train.sh', I found that there's no 'path3' for both suffix and data_dir. 
After this modification, the model seems working.
Thank you for your help!

**Comment by zhw12** [comment]
Yes, I think so. Those suffix name should match.
