### ISSUE TITLE
Hello! I have a question about why use MRPC not MNLI manner?

### ISSUE THREAD

**Issue by orangezfj** [zhw12/BERTRL#4]

**Comment by orangezfj** [comment]
There no explain in paper. If someone have answer, please tell me. Thanks!

**Comment by orangezfj** [comment]
I guss this is a pair of instances samilify I guess it's about judging similarity between instances

**Comment by An-Kuen** [comment]
The code not use the train.tsv in bertrl_data as train dataset, why? I not see any code use that file.
